version: '3'

services:
  web:
    build: .
    command: ['scripts/dev.sh']
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../readme_tw_backend/postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ../readme_tw_backend
    command: ["scripts/wait-for-it.sh", "db:5432", "--", "scripts/dev.sh"]
    environment:
      DJANGO_DEBUG: 'True'
      DJANGO_SETTINGS_MODULE: "readme_be.settings"
      DJANGO_LOG_LEVEL: "DEBUG"
    volumes:
      - ../readme_tw_backend:/code
    ports:
      - "8080:8080"