version: '3'

services:
  web:
    build: .
    command: ['scripts/prod.sh']
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    ports:
      - "9000:9000"

volumes:
  node_modules:
