version: '3'

services:
  web:
    build: .
    command: ['scripts/dev.sh']
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    ports:
      - "8000:8000"

volumes:
  node_modules: